export const Category = {
    ATM: "ATM",
    AUTOMOTIVE: "AUTOMOTIVE",
    DIGITAL_SERVICES: "DIGITAL_SERVICES",
    EDUCATION: "EDUCATION",
    ENTERTAINMENT: "ENTERTAINMENT",
    FEES_AND_CHARGES: "FEES_AND_CHARGES",
    FINANCE: "FINANCE",
    FOOD_AND_DRINK: "FOOD_AND_DRINK",
    GIFTS_AND_DONATIONS: "GIFTS_AND_DONATIONS",
    GOVERNMENT: "GOVERNMENT",
    GROCERIES: "GROCERIES",
    HEALTHCARE: "HEALTHCARE",
    HOME: "HOME",
    INSURANCE: "INSURANCE",
    PERSONAL_CARE: "PERSONAL_CARE",
    PET_CARE: "PET_CARE",
    SERVICES: "SERVICES",
    SHOPPING: "SHOPPING",
    SPORTS_AND_FITNESS: "SPORTS_AND_FITNESS",
    TRANSPORT: "TRANSPORT",
    TRAVEL: "TRAVEL",
    UTILITIES: "UTILITIES",
} as const;

export type Category = (typeof Category)[keyof typeof Category];

export const CATEGORIES = Object.values(Category);
